#!/usr/bin/env python3

import datetime
import time
import logging

from config import Config
from manager import Manager
from syncqueue import SyncQueue
import userinput
import screen
from screenmsg import ScreenMessage

if __name__ == '__main__':
    debug = True

    # initialize queues
    scr_queue = SyncQueue(ScreenMessage)
    
    # load config
    cfg = Config()
    cfg.auto_load_on_change()

    # initialize threads
    scr = screen.create(debug, scr_queue)
    scr.start()
    #scr.run()

    # initialize
    user_input = userinput.create(debug)
    mgr = Manager(scr_queue)

    # main loop
    next_update = datetime.datetime.now() + datetime.timedelta(seconds=1)
    while True:
        # read and act on inputs
        event = user_input.get_event(scr.get_data())
        if event:
            mgr.do_event(event)

        # yield to other threads
        time.sleep(0.01)
