#!/usr/bin/env python3

import datetime
import time
import logging

from config import Config
from manager import Manager
import userinput
import screen

cfg = None
debug = True

if __name__ == '__main__':
    # load config
    cfg = Config()
    cfg.auto_load_on_change()

    # initialize threads
    scr = screen.create(debug)
    if debug:
        logging.basicConfig(level=logging.DEBUG)
        logging.getLogger().handlers = []
        logging.getLogger().addHandler(scr)
        logging.debug("Screen initialized.")
    scr.start()
    #scr.run()

    # initialize
    user_input = userinput.create(debug)
    mgr = Manager()
    
    # main loop
    next_update = datetime.datetime.now() + datetime.timedelta(seconds=1)
    while True:
        # read and act on inputs
        event = user_input.get_event(scr.get_data())
        if event:
            mgr.do_event(event)

        # yield to other threads
        time.sleep(0.01)
